= Metodologia para mitigar o viés de similaridade nas bases de dados de MFPT e Paderborn

== Introdução

Os processos industriais são constantemente monitorados para o fornecimento de produtos de melhor qualidade e com menores taxas de rejeição.
Porém, durante a produção podem ocorrer falhas durante os processos, que são definidas como um desvio não permitido de ao menos uma variável ou propriedade característica do sistema <<isermann1997>>.
Os rolamentos são indispensáveis para máquinas com partes rotativas e o monitoramento de falhas nesses componentes é importante, uma vez que 40 a 50% das falhas de equipamentos que os possuem são causadas por falhas neles <<nandi2005>>.

O monitoramento de processos industriais pode ser dividido em quatro etapas: detecção de falhas, identificação de falhas, diagnóstico de falhas e processo de recuperação <<chiang2001>>.
Dentre essas etapas, o diagnóstico de falhas pode ser aplicado através de sistemas baseados em _softwares_, que são considerados ferramentas essenciais para garantir a segurança e manutenção de processos dinâmicos <<chiang2001>>.
Esses sistemas podem utilizar técnicas de aprendizado de máquina, que usam os sinais coletados de determinado equipamento para treinar e testar classificadores, e então identificar e diagnosticar as falhas <<rauber2020>>.

O desenvolvimento de modelos para classificação de falhas em rolamento depende da utilização de bases de dados com sinais coletados durante o funcionamento de um equipamento, que são separados em parte para treinamento e validação e parte para testes, de onde são extraídos os resultados dos experimentos.
Porém, dependendo das escolhas durante a elaboração do modelo, os experimentos podem trazer uma avaliação super otimista, onde os resultados foram adequados apenas para a configuração utilizada.
Desta forma, quando a técnica testada for aplicada na prática, possivelmente não trará resultados similares aos obtidos durante o desenvolvimento.
Uma avaliação realista deve levar em consideração a capacidade de generalização do modelo elaborado.
Assim o classificador treinado deve ser capaz de reconhecer o máximo de condições possíveis, mesmo quando há variações em suas condições de trabalho <<rauber2020>>.

Uma característica que influencia na capacidade de generalização de um algoritmo, de acordo com <<rauber2020>>, é o viés de similaridade.
O viés de similaridade ocorre quando os dados de uma mesma condição que são utilizados para o treinamento e teste do modelo têm características muito similares, tornando a tarefa de classificação relativamente trivial.
Amostras de uma mesma condição e de uma mesma aquisição, por exemplo, tipicamente são muito similares <<rauber2020>>.
Em <<rauber2020>>, são realizados experimentos com a base de dados fornecida pela _Case Western Reserve University_ (CWRU) com diferentes formas de separação dos dados a fim de verificar a questão do viés de similaridade.
O artigo apresenta uma extensa lista de trabalhos publicados não considera esse viés no desenvolvimento de seus modelos.

As bases de dados disponibilizadas pela _Machinery Failure Prevention Technology Society_ (MFPT) e pela _Konstruktions und Antriebstechnik_ da Universidade de Paderborn (PADERBORN) são utilizadas para o desenvolvimento de modelos de classificação de falhas em diversos artigos.
A tabela XXX apresenta trabalhos publicados com detalhes sobre a forma de separação dos dados para o treinamento e testes dos modelos.
A questão do viés de similaridade não é considerada na elaboração dos algoritmos de classificação de falhas dos artigos listados.

Em <<zhao2020>>, que realiza um estudo com a aplicação de métodos de aprendizado profundo em 9 bases de dados de falhas de rolamentos, incluindo a base MFPT e a Paderborn, são descritas duas formas de separação dos dados em treinamento e testes
Uma é a separação randômica dos dados, onde as amostras são escolhidas aleatoriamente para treino e teste.
Outra é a separação pelo tempo, onde um percentual ou duração pré-definida do sinal é escolhido para treino e teste.
Em ambos os casos, são utilizadas amostras da mesma aquisição para treino e teste, e o viés de similaridade pode ocorrer.

Dentre os artigos que utilizam a base MFPT, em <<wang2020>>, que propõe uma __lightweight convolutional neural network__ (LCNN), é realizada a separação dos dados aleatoriamente com 70% para treinamento, 10% para validação e 20% para teste, também utilizando amostras de mesma aquisição em todos.
<<verstraete2017>> propõe uma metologia baseada em __deep learning__ para aprendizado automático de características dos dados, onde a separação dos dados também foi realizada aleatoriamente com 70% para treinamento e 30% para teste, com amostras de mesma aquisição em ambos.
Muitos trabalhos não informam a forma de separação de dados, como em <<wen2019>>, que propõe uma nova __snapshot ensemble convolutional neural network__ (SECNN), e em <<lee2016>>, que avalia o uso de __convolutional neural nets__ (CNN) diretamente nos sinais.

Para os artigos onde a base Paderborn é utilizada, alguns utilizam dados de mesma aquisição tanto para o treinamento como para o teste como já citado em <<zhao2020>>.
Entre eles <<hou2020>>, que propõe uma __deep residual network__ (ResNet) baseada em __input feature mappings__ (IFMs).
Outros artigos realizam experimentos onde não são utilizados dados de mesma aquisição para treino e teste simultaneamente, como em <<chen2018>>, que propõe uma __deep inception net__ com __atrous convolution__ (ACDIN) para tratar do problema de utilizar dados de danos artificiais com mais confiabilidade, e em <<zhu2018>>, que propõe uma nova __capsule network__.
Para esses casos, a separação não considerando a aquisição não foi com o objetivo explícito de evitar algum viés de similaridade.
Porém, para a base PADERBORN, o viés de similaridade pode ocorrer não somente pela utilização de mesma aquisição, mas também de outras formas, como dados de mesmo rolamento com mesma carga, ou até de mesmo rolamento, a ser confirmado com experimentos.

Uma forma de mitigar o viés de similaridade, e aumentar a capacidade de generalização de um modelo de classificação de falhas em rolamentos, é a não utilização de amostras de mesma condição e aquisição no treinamento e teste.
Para isso, deve-se definir grupos diferentes para cada aquisição e/ou outras características, para que os dados de tais grupos sejam utilizados somente para treinamento ou para testes.

[bibliography]
== Bibliografia
. [[isermann1997]] R. Isermann & P. Ballé. _Trends in the application of model-based fault detection and diagnosis of technical processes_. Control engineering practice. 1997.
. [[chiang2001]] L.H. Chiang, E.L. Russell, R.D. Braatz. _Fault detection and diagnosis in industrial systems_. Springer. 2001.
. [[rauber2020]]  Thomas Walter Rauber. _An experimental methodology to evaluate machine learning methods for fault diagnosis based on vibration signals_. Expert Systems With Applications. 2020.
. [[nandi2005]]  S. Nandi, H.A. Toliyat, X. Li. _Condition monitoring and fault diagnosis of electrical motors—A review_. IEEE transactions on energy. 2005.
. [[zhao2020]]  Z. Zhao, T. Li, J. Wu, C. Sun, S. Wang, R. Yan, X. Chen. _Deep Learning Algorithms for Rotating Machinery Intelligent Diagnosis: An Open Source Benchmark Study_. ISA Transactions. 2020.
. [[wang2020]]  Y. Wang, J. Yan, Q. Sun, Q. Jiang, Y. Zhou. _Bearing Intelligent Fault Diagnosis in the Industrial Internet of Things Context: A Lightweight Convolutional Neural Network_. IEEE Access. 2020.
. [[verstraete2017]]  D. Verstraete, A. Ferrada, E.L. Droguett, V. Meruane. _Deep Learning Enabled Fault Diagnosis Using Time-Frequency Image Analysis of Rolling Element Bearings_. Shock and Vibration. 2017.
. [[wen2019]]  L. Wen, L. Gao, X. Li. _A New Snapshot Ensemble Convolutional Neural Network for Fault Diagnosis_. IEEE Access. 2019.
. [[lee2016]]  D. Lee, V. Siu, R. Cruz, C. Yetman. _Convolutional neural net and bearing fault analysis_. International Conference on Data Mining. 2016.
. [[hou2020]]  L. Hou, R. Jiang, Y. Tan, J. Zhang. _Input Feature Mappings-Based Deep Residual Networks for Fault Diagnosis of Rolling Element Bearing With Complicated Dataset_. IEEE Access. 2020.
. [[chen2018]]  Y. Chen, G. Peng, C. Xie, W. Zhang, C. Li, S. Liu. _ACDIN: Bridging the gap between artificial and real bearing damages for bearing fault diagnosis_. Neurocomputing. 2018.
. [[zhu2018]]  Z. Zhu, G. Peng, Y. Chen, H. Gao. _A convolutional neural network based on a capsule network with strong generalization for bearing fault diagnosis_. Neurocomputing. 2018.
