= Metodologia para mitigar o viés de similaridade nas bases de dados de MFPT e Paderborn

A capacidade de generalização de algoritmos de diagnóstico de falhas em rolamentos representa o desempenho de um modelo elaborado quando é utilizado em diferentes condições de funcionamento de determinado equipamento. Assim, um modelo desenvolvido com dados de uma condição tende a ter uma performance significativamente inferior quando aplicado em outras condições, o que na prática é o cenário mais provável. Logo, os resultados obtidos durante a elaboração do modelo com uma ou poucas condições de trabalho do equipamento podem ser otimistas e com resultados insatisfatórios quando aplicados na realidade.

Além da não utilização de diferentes condições na elaboração do modelo para diagnóstico de falhas, outra característica que influencia na capacidade de generalização de um algoritmo, de acordo com (1), é o viés de similaridade. O viés de similaridade ocorre quando os dados de uma mesma condição que são utilizados para o treinamento e teste do modelo têm características muito similares, tornando a tarefa de classificação relativamente trivial. Amostras de uma mesma condição e de uma mesma aquisição, por exemplo, tipicamente são muito similares (1). Em (1), são realizados experimentos com a base CWRU com diferentes formas de separação dos dados a fim de verificar a questão do viés de similaridade, indicando também que uma extensa lista de trabalhos publicados não considera esse viés no desenvolvimento de seus modelos.

Os trabalhos publicados para as bases de dados MFPT e Paderborn também não consideram a questão do viés de similaridade na elaboração dos algoritmos de classificação de falhas (elaborar tabela com principais trabalhos de cada base e suas formas de separação de dados).

Em (10), que realiza um estudo com a aplicação de métodos de aprendizado profundo em 9 bases de dados de falhas de rolamentos, incluindo a base MFPT e a Paderborn, são descritas duas formas de separação dos dados em treinamento e testes: separação randômica dos dados, onde as amostras são escolhidas aleatoriamente para treino e teste; separação pelo tempo, onde um percentual ou duração pré-definida do sinal é escolhido para treino e teste. Em ambos os casos, ainda são utilizadas amostras da mesma condição e aquisição para treino e teste.

Dentre os artigos que utilizam a base MFPT, em (5), que propõe uma __lightweight convolutional neural network__ (LCNN), é realizada a separação dos dados aleatoriamente com 70% para treinamento, 10% para validação e 20% para teste, também utilizando amostras de mesma aquisição em todos. Em (6), que propõe uma metologia baseada em __deep learning__ par aprendizado automático de características dos dados, a separação de também foi realizada aleatoriamente com 70% para treinamento e 30% para teste, com amostras de mesma aquisição em ambos. Muitos trabalhos não informam a forma de separação de dados, como em (2), que propõe uma nova __snapshot ensemble convolutional neural network__ (SECNN), e em (7), que avalia o uso de __convolutional neural nets__ (CNN) diretamente nos sinais.

Para os artigos onde a base Paderborn é utilizada, alguns utilizam dados de mesma aquisição tanto para o treinamento como para o teste como já citado em (10), entre eles em (15), que propõe uma __deep residual network__ (ResNet) baseada em __input feature mappings__ (IFMs). Outros artigos realizam experimentos onde não são utilizados dados de mesma aquisição para treino e teste simultaneamente, como em (13), que propõe uma __deep inception net__ com __atrous convolution__ (ACDIN) para tratar do problema de utilizar dados de danos artificiais com mais confiabilidade, e em (14), que propõe uma nova __capsule network__. Para esses casos, a separação não considerando a aquisição não foi com o objetivo explícito de evitar algum viés. Porém, para o Paderborn, o viés de similaridade pode ocorrer não somente pela utilização de mesma aquisição, mas também de outras formas, como dados de mesmo rolamento com mesma carga, ou até de mesmo rolamento, a ser confirmado com experimentos.

Uma forma de mitigar o viés de similaridade e aumentar a capacidade de generalização de um modelo de classificação de falhas em rolamentos com a não utilização de amostras de mesma condição e aquisição no treinamento e teste é a definição de grupos diferentes para cada aquisição e/ou outras características e que tais grupos sejam mantidos sempre para treinamento ou para testes.
